name: Build CinematicUnityExplorer

# Controls when the action will run.
on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_dotnet:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '-noci')"

    steps:
      # Setup

      - name: Checkout latest
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"
      # Run build script
      - name: Build UE
        run: ./build.ps1

      #  Upload artifacts
      - name: Upload MelonLoader.IL2CPP.CoreCLR
        uses: actions/upload-artifact@v4
        with:
          name: CinematicUnityExplorer.MelonLoader.IL2CPP.CoreCLR.zip
          path: ./Release/CinematicUnityExplorer.MelonLoader.IL2CPP.CoreCLR/

  build_connector:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '-noci')"

    steps:
      - name: Checkout latest
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup C/C++
        uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
        with:
          arch: x64

      # Run build script
      - name: Build Unity IGCS Connector
        run: ./build_connector.ps1

      - name: Upload Unity IGCS Connector
        uses: actions/upload-artifact@v4
        with:
          name: UnityIGCSConnector.dll
          path: ./Release/UnityIGCSConnector.dll

      - name: Upload Unity IGCS Connector 32bit
        uses: actions/upload-artifact@v4
        with:
          name: UnityIGCSConnector.32.dll
          path: ./Release/UnityIGCSConnector.32.dll
